[package]
name = "master-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.22"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
simd-json = "0.13.6"
sqlx = { version = "0.7.3", features = ["sqlite", "runtime-tokio-native-tls", "chrono", "macros"] }
tar = "0.4.38"
tokio = { version = "1", features = ["full"] }
tokio-test = "0.4.3"
ureq = "2.5.0"
zstd = "0.13"

[profile.release]
debug = false
codegen-units = 1
lto = true
